### PR TITLE
Remove unnecessary dependencies

### PR DESCRIPTION
**Pull request by jeongseok-meta**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Review by h-vetinari — COMMENTED** [review]
Please fully revert #6, including the additions to host/run environments.

**Comment by jeongseok-meta** [comment]
It seems the linux builds work without them, where I still don't know what's been changed as it failed without them before. Anyways, thank you for helping keep the package clean and nice to follow the convention!

**Comment by h-vetinari** [comment]
> I still don't know what's been changed as it failed without them before.

There was a gap between the merge of https://github.com/conda-forge/ctng-compilers-feedstock/pull/148 & https://github.com/conda-forge/ctng-compiler-activation-feedstock/pull/126 during which it was possible to run into this problem, but only on feedstocks doing
https://github.com/conda-forge/dispenso-feedstock/blob/bae23c71b23e759c5111872d19ba11ec598f26a3/conda-forge.yml#L12

**Comment by jeongseok-meta** [comment]
Ah, good to know. Thank you again for gatekeeping! Merging now!

**Pull request merged**
